services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      REFRESH_JWT_SECRET: ${REFRESH_JWT_SECRET}
      REFRESH_EXPIRES_IN: ${REFRESH_EXPIRES_IN}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
      target: dev
    container_name: backend
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public"
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      REFRESH_JWT_SECRET: ${REFRESH_JWT_SECRET}
      REFRESH_EXPIRES_IN: ${REFRESH_EXPIRES_IN}
    depends_on:
      db:
        condition: service_healthy
    command: sh -lc "npm i && npm run dev"
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: frontend
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      VITE_API_BASE: http://localhost:${BACKEND_PORT}
      CHOKIDAR_USEPOLLING: "1"
    command: sh -lc "npm i && npm run dev -- --host 0.0.0.0 --port ${FRONTEND_PORT}"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
volumes:
  dbdata:
